//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAWPF.Res.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFAWPF.Res.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕获模式: 的本地化字符串。
        /// </summary>
        internal static string AdbCaptureMode {
            get {
                return ResourceManager.GetString("AdbCaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 额外参数 的本地化字符串。
        /// </summary>
        internal static string AdbConfig {
            get {
                return ResourceManager.GetString("AdbConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adb 编辑器 的本地化字符串。
        /// </summary>
        internal static string AdbEditor {
            get {
                return ResourceManager.GetString("AdbEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdbInput (不推荐) 的本地化字符串。
        /// </summary>
        internal static string AdbInput {
            get {
                return ResourceManager.GetString("AdbInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触控模式: 的本地化字符串。
        /// </summary>
        internal static string AdbInputMode {
            get {
                return ResourceManager.GetString("AdbInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adb名称 的本地化字符串。
        /// </summary>
        internal static string AdbName {
            get {
                return ResourceManager.GetString("AdbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adb路径 的本地化字符串。
        /// </summary>
        internal static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adb地址 的本地化字符串。
        /// </summary>
        internal static string AdbSerial {
            get {
                return ResourceManager.GetString("AdbSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加至上方 的本地化字符串。
        /// </summary>
        internal static string AddAbove {
            get {
                return ResourceManager.GetString("AddAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加至下方 的本地化字符串。
        /// </summary>
        internal static string AddBelow {
            get {
                return ResourceManager.GetString("AddBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        internal static string AdvancedSetting {
            get {
                return ResourceManager.GetString("AdvancedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束后操作 的本地化字符串。
        /// </summary>
        internal static string AfterTaskOption {
            get {
                return ResourceManager.GetString("AfterTaskOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MFA 任务管理器 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoDetect (自动检测) 的本地化字符串。
        /// </summary>
        internal static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动后操作 的本地化字符串。
        /// </summary>
        internal static string AutoStartOption {
            get {
                return ResourceManager.GetString("AutoStartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕获方式 的本地化字符串。
        /// </summary>
        internal static string CaptureModeOption {
            get {
                return ResourceManager.GetString("CaptureModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前剪贴板中数据不可转换为文本 的本地化字符串。
        /// </summary>
        internal static string ClipboardDataError {
            get {
                return ResourceManager.GetString("ClipboardDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭模拟器 的本地化字符串。
        /// </summary>
        internal static string CloseEmulator {
            get {
                return ResourceManager.GetString("CloseEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭MFA和模拟器 的本地化字符串。
        /// </summary>
        internal static string CloseEmulatorAndMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启MFA和关闭模拟器 的本地化字符串。
        /// </summary>
        internal static string CloseEmulatorAndRestartMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndRestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭MFA 的本地化字符串。
        /// </summary>
        internal static string CloseMFA {
            get {
                return ResourceManager.GetString("CloseMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取色器 的本地化字符串。
        /// </summary>
        internal static string ColorPickerTitle {
            get {
                return ResourceManager.GetString("ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通设置 的本地化字符串。
        /// </summary>
        internal static string CommonSetting {
            get {
                return ResourceManager.GetString("CommonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接{0}时发生错误！ 的本地化字符串。
        /// </summary>
        internal static string ConnectingEmulatorOrWindow {
            get {
                return ResourceManager.GetString("ConnectingEmulatorOrWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在连接至{0}...... 的本地化字符串。
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪切板 的本地化字符串。
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制错误信息 的本地化字符串。
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制键 的本地化字符串。
        /// </summary>
        internal static string CopyKey {
            get {
                return ResourceManager.GetString("CopyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制值 的本地化字符串。
        /// </summary>
        internal static string CopyValue {
            get {
                return ResourceManager.GetString("CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        internal static string DarkColor {
            get {
                return ResourceManager.GetString("DarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部不选 的本地化字符串。
        /// </summary>
        internal static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipeline文件中存在重复的任务名称:&quot;{0}&quot;！ 的本地化字符串。
        /// </summary>
        internal static string DuplicateTaskError {
            get {
                return ResourceManager.GetString("DuplicateTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表中已存在命名为&quot;{0}&quot;的任务 的本地化字符串。
        /// </summary>
        internal static string DuplicateTaskNameError {
            get {
                return ResourceManager.GetString("DuplicateTaskNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性编辑器 的本地化字符串。
        /// </summary>
        internal static string EditAttributeDialogTitle {
            get {
                return ResourceManager.GetString("EditAttributeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑任务 的本地化字符串。
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加属性 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_AddAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_AddAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加任务 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_AddTask_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_AddTask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空属性 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_ClearAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空任务 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_ClearTask_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearTask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取色 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_ColorExtraction_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ColorExtraction_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务编辑器 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_Header {
            get {
                return ResourceManager.GetString("EditTaskDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Pipeline文件 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_Load_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Load_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipeline文件名称 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_PipelineFileName_Placeholder {
            get {
                return ResourceManager.GetString("EditTaskDialog_PipelineFileName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字识别 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_RecognitionText_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_RecognitionText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存Pipeline文件 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_SavePipeline_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SavePipeline_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存任务名称 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_SaveTask_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_SaveTask_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 裁剪图片 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_Screenshot_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Screenshot_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择区域 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_SelectionRegion_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SelectionRegion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程图 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_ShowChart_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_ShowChart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑动 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_Swipe_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Swipe_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表： 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_TaskList_Label {
            get {
                return ResourceManager.GetString("EditTaskDialog_TaskList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称: 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_TaskName_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_TaskName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务编辑器 的本地化字符串。
        /// </summary>
        internal static string EditTaskDialog_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑任务 的本地化字符串。
        /// </summary>
        internal static string EditTaskTooltip {
            get {
                return ResourceManager.GetString("EditTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟器 的本地化字符串。
        /// </summary>
        internal static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始搜索模拟器! 的本地化字符串。
        /// </summary>
        internal static string EmulatorDetectionStarted {
            get {
                return ResourceManager.GetString("EmulatorDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟器路径 的本地化字符串。
        /// </summary>
        internal static string EmulatorPath {
            get {
                return ResourceManager.GetString("EmulatorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择模拟器:{0} 的本地化字符串。
        /// </summary>
        internal static string EmulatorSelectionMessage {
            get {
                return ResourceManager.GetString("EmulatorSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入任务名称 的本地化字符串。
        /// </summary>
        internal static string EnterTaskName {
            get {
                return ResourceManager.GetString("EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        internal static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MFA 遇到了问题 的本地化字符串。
        /// </summary>
        internal static string ErrorProlog {
            get {
                return ResourceManager.GetString("ErrorProlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可运行文件 (*.exe*)|*.exe* 的本地化字符串。
        /// </summary>
        internal static string ExeFilter {
            get {
                return ResourceManager.GetString("ExeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        internal static string FollowingSystem {
            get {
                return ResourceManager.GetString("FollowingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片浏览器 的本地化字符串。
        /// </summary>
        internal static string ImageBrowserTitle {
            get {
                return ResourceManager.GetString("ImageBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件 (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp 的本地化字符串。
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化控制器时发生错误！ 的本地化字符串。
        /// </summary>
        internal static string InitControllerFailed {
            get {
                return ResourceManager.GetString("InitControllerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化控制器成功 的本地化字符串。
        /// </summary>
        internal static string InitControllerSuccess {
            get {
                return ResourceManager.GetString("InitControllerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化MAA实例失败，发生连接错误或资源文件损坏，请参阅日志. 的本地化字符串。
        /// </summary>
        internal static string InitInstanceFailed {
            get {
                return ResourceManager.GetString("InitInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入资源成功 的本地化字符串。
        /// </summary>
        internal static string InitResourcesSuccess {
            get {
                return ResourceManager.GetString("InitResourcesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触控模式 的本地化字符串。
        /// </summary>
        internal static string InputModeOption {
            get {
                return ResourceManager.GetString("InputModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string InstanceInitFailedLog {
            get {
                return ResourceManager.GetString("InstanceInitFailedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON 文件 (*.json)|*.json|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string JSONFilter {
            get {
                return ResourceManager.GetString("JSONFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性类型: 的本地化字符串。
        /// </summary>
        internal static string LabelPropertyType {
            get {
                return ResourceManager.GetString("LabelPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言(Language) 的本地化字符串。
        /// </summary>
        internal static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        internal static string LightColor {
            get {
                return ResourceManager.GetString("LightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 任意 文件 的本地化字符串。
        /// </summary>
        internal static string LoadFileTitle {
            get {
                return ResourceManager.GetString("LoadFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片文件 的本地化字符串。
        /// </summary>
        internal static string LoadImageTitle {
            get {
                return ResourceManager.GetString("LoadImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化控制器 的本地化字符串。
        /// </summary>
        internal static string LoadingController {
            get {
                return ResourceManager.GetString("LoadingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在载入资源 的本地化字符串。
        /// </summary>
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipeline文件加载或解析失败: {0} 的本地化字符串。
        /// </summary>
        internal static string LoadPipelineErrorMessage {
            get {
                return ResourceManager.GetString("LoadPipelineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Pipeline 文件 的本地化字符串。
        /// </summary>
        internal static string LoadPipelineTitle {
            get {
                return ResourceManager.GetString("LoadPipelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源加载失败！ 的本地化字符串。
        /// </summary>
        internal static string LoadResourcesFailed {
            get {
                return ResourceManager.GetString("LoadResourcesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaaTouch (实验功能) 的本地化字符串。
        /// </summary>
        internal static string MaaTouch {
            get {
                return ResourceManager.GetString("MaaTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiniTouch (默认) 的本地化字符串。
        /// </summary>
        internal static string MiniTouch {
            get {
                return ResourceManager.GetString("MiniTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到模拟器! 的本地化字符串。
        /// </summary>
        internal static string NoEmulatorFound {
            get {
                return ResourceManager.GetString("NoEmulatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有可结束的任务! 的本地化字符串。
        /// </summary>
        internal static string NoTaskToStop {
            get {
                return ResourceManager.GetString("NoTaskToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到窗口! 的本地化字符串。
        /// </summary>
        internal static string NoWindowFound {
            get {
                return ResourceManager.GetString("NoWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴到上方 的本地化字符串。
        /// </summary>
        internal static string PasteAbove {
            get {
                return ResourceManager.GetString("PasteAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴到下方 的本地化字符串。
        /// </summary>
        internal static string PasteBelow {
            get {
                return ResourceManager.GetString("PasteBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入Pipeline文件时出现错误: {0} 的本地化字符串。
        /// </summary>
        internal static string PipelineLoadError {
            get {
                return ResourceManager.GetString("PipelineLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目链接:  的本地化字符串。
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域选择器 的本地化字符串。
        /// </summary>
        internal static string RegionSelectorTitle {
            get {
                return ResourceManager.GetString("RegionSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册自定义Action:{0} 的本地化字符串。
        /// </summary>
        internal static string RegisterCustomAction {
            get {
                return ResourceManager.GetString("RegisterCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册自定义Recognizer:{0} 的本地化字符串。
        /// </summary>
        internal static string RegisterCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisterCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在注册自定义行动 的本地化字符串。
        /// </summary>
        internal static string RegisteringCustomAction {
            get {
                return ResourceManager.GetString("RegisteringCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在注册自定义识别器 的本地化字符串。
        /// </summary>
        internal static string RegisteringCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisteringCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住连接 的本地化字符串。
        /// </summary>
        internal static string RememberAdb {
            get {
                return ResourceManager.GetString("RememberAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复次数 的本地化字符串。
        /// </summary>
        internal static string RepeatOption {
            get {
                return ResourceManager.GetString("RepeatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源链接:  的本地化字符串。
        /// </summary>
        internal static string ResourceLink {
            get {
                return ResourceManager.GetString("ResourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源名称 的本地化字符串。
        /// </summary>
        internal static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源 的本地化字符串。
        /// </summary>
        internal static string ResourceOption {
            get {
                return ResourceManager.GetString("ResourceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源版本 的本地化字符串。
        /// </summary>
        internal static string ResourceVersion {
            get {
                return ResourceManager.GetString("ResourceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启系统 的本地化字符串。
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启MFA 的本地化字符串。
        /// </summary>
        internal static string RestartMFA {
            get {
                return ResourceManager.GetString("RestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存任务失败! 的本地化字符串。
        /// </summary>
        internal static string SaveFailureMessage {
            get {
                return ResourceManager.GetString("SaveFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        internal static string SavePipelineSuccess {
            get {
                return ResourceManager.GetString("SavePipelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表中存在相同命名的任务! 的本地化字符串。
        /// </summary>
        internal static string SavePipelineWarning {
            get {
                return ResourceManager.GetString("SavePipelineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存任务成功! 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图耗时: {0}ms({1}) 的本地化字符串。
        /// </summary>
        internal static string ScreenshotTime {
            get {
                return ResourceManager.GetString("ScreenshotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择可运行文件 的本地化字符串。
        /// </summary>
        internal static string SelectExecutableFile {
            get {
                return ResourceManager.GetString("SelectExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机 的本地化字符串。
        /// </summary>
        internal static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑动获取器 的本地化字符串。
        /// </summary>
        internal static string SliderControlTitle {
            get {
                return ResourceManager.GetString("SliderControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动MFA后启动模拟器 的本地化字符串。
        /// </summary>
        internal static string StartEmulator {
            get {
                return ResourceManager.GetString("StartEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动任务 的本地化字符串。
        /// </summary>
        internal static string StartTask {
            get {
                return ResourceManager.GetString("StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动参数 的本地化字符串。
        /// </summary>
        internal static string StartupParameter {
            get {
                return ResourceManager.GetString("StartupParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动脚本 的本地化字符串。
        /// </summary>
        internal static string StartupScript {
            get {
                return ResourceManager.GetString("StartupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止...... 的本地化字符串。
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止任务失败 的本地化字符串。
        /// </summary>
        internal static string StoppingFailed {
            get {
                return ResourceManager.GetString("StoppingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止任务 的本地化字符串。
        /// </summary>
        internal static string StopTask {
            get {
                return ResourceManager.GetString("StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换配置 的本地化字符串。
        /// </summary>
        internal static string SwitchConfiguration {
            get {
                return ResourceManager.GetString("SwitchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADB 的本地化字符串。
        /// </summary>
        internal static string TabADB {
            get {
                return ResourceManager.GetString("TabADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 的本地化字符串。
        /// </summary>
        internal static string TabWin32 {
            get {
                return ResourceManager.GetString("TabWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已放弃本次任务 的本地化字符串。
        /// </summary>
        internal static string TaskAbandoned {
            get {
                return ResourceManager.GetString("TaskAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已全部完成！ 的本地化字符串。
        /// </summary>
        internal static string TaskAllCompleted {
            get {
                return ResourceManager.GetString("TaskAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已全部完成！\n(用时 {0}h {1}m {2}s) 的本地化字符串。
        /// </summary>
        internal static string TaskAllCompletedWithTime {
            get {
                return ResourceManager.GetString("TaskAllCompletedWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已完成 的本地化字符串。
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表： 的本地化字符串。
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表： 的本地化字符串。
        /// </summary>
        internal static string TaskListHeader {
            get {
                return ResourceManager.GetString("TaskListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipeline文件中任务的{0}使用了不存在的任务:&quot;{1}&quot;！ 的本地化字符串。
        /// </summary>
        internal static string TaskNotFoundError {
            get {
                return ResourceManager.GetString("TaskNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务设置 的本地化字符串。
        /// </summary>
        internal static string TaskSettings {
            get {
                return ResourceManager.GetString("TaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别{0}时发生错误: {1} 的本地化字符串。
        /// </summary>
        internal static string TaskStackError {
            get {
                return ResourceManager.GetString("TaskStackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始任务: {0} 的本地化字符串。
        /// </summary>
        internal static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已中止 的本地化字符串。
        /// </summary>
        internal static string TaskStopped {
            get {
                return ResourceManager.GetString("TaskStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字识别器 的本地化字符串。
        /// </summary>
        internal static string TextRecognizerTitle {
            get {
                return ResourceManager.GetString("TextRecognizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色主题 的本地化字符串。
        /// </summary>
        internal static string ThemeOption {
            get {
                return ResourceManager.GetString("ThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签顺序可拖动 的本地化字符串。
        /// </summary>
        internal static string TooltipDragLabel {
            get {
                return ResourceManager.GetString("TooltipDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string TooltipRefresh {
            get {
                return ResourceManager.GetString("TooltipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string TooltipSettings {
            get {
                return ResourceManager.GetString("TooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待模拟器启动时间(秒) 的本地化字符串。
        /// </summary>
        internal static string WaitEmulator {
            get {
                return ResourceManager.GetString("WaitEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待模拟器启动时间(秒): {0}(s) 的本地化字符串。
        /// </summary>
        internal static string WaitEmulatorTime {
            get {
                return ResourceManager.GetString("WaitEmulatorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接至{0} 的本地化字符串。
        /// </summary>
        internal static string Warning_CannotConnect {
            get {
                return ResourceManager.GetString("Warning_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始搜索窗口! 的本地化字符串。
        /// </summary>
        internal static string WindowDetectionStarted {
            get {
                return ResourceManager.GetString("WindowDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择窗口:{0} 的本地化字符串。
        /// </summary>
        internal static string WindowSelectionMessage {
            get {
                return ResourceManager.GetString("WindowSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务流程图 的本地化字符串。
        /// </summary>
        internal static string WorkflowDiagramTitle {
            get {
                return ResourceManager.GetString("WorkflowDiagramTitle", resourceCulture);
            }
        }
    }
}
