//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAWPF.Res.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFAWPF.Res.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获模式:.
        /// </summary>
        internal static string AdbCaptureMode {
            get {
                return ResourceManager.GetString("AdbCaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式:.
        /// </summary>
        internal static string AdbInputMode {
            get {
                return ResourceManager.GetString("AdbInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maa框架任务管理器.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获方式.
        /// </summary>
        internal static string CaptureModeOption {
            get {
                return ResourceManager.GetString("CaptureModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部不选.
        /// </summary>
        internal static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部不选.
        /// </summary>
        internal static string DeselectAllTooltip {
            get {
                return ResourceManager.GetString("DeselectAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中存在重复的任务名称:&quot;{0}&quot;！.
        /// </summary>
        internal static string DuplicateTaskError {
            get {
                return ResourceManager.GetString("DuplicateTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        internal static string EditTaskTooltip {
            get {
                return ResourceManager.GetString("EditTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索模拟器!.
        /// </summary>
        internal static string EmulatorDetectionStarted {
            get {
                return ResourceManager.GetString("EmulatorDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择模拟器:{0}.
        /// </summary>
        internal static string EmulatorSelectionMessage {
            get {
                return ResourceManager.GetString("EmulatorSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言(Language).
        /// </summary>
        internal static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到模拟器!.
        /// </summary>
        internal static string NoEmulatorFound {
            get {
                return ResourceManager.GetString("NoEmulatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到窗口!.
        /// </summary>
        internal static string NoWindowFound {
            get {
                return ResourceManager.GetString("NoWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入Pipeline文件时出现错误: {0}.
        /// </summary>
        internal static string PipelineLoadError {
            get {
                return ResourceManager.GetString("PipelineLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复次数.
        /// </summary>
        internal static string RepeatOption {
            get {
                return ResourceManager.GetString("RepeatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源.
        /// </summary>
        internal static string ResourceOption {
            get {
                return ResourceManager.GetString("ResourceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        internal static string SelectAllTooltip {
            get {
                return ResourceManager.GetString("SelectAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动任务.
        /// </summary>
        internal static string StartTask {
            get {
                return ResourceManager.GetString("StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止任务.
        /// </summary>
        internal static string StopTask {
            get {
                return ResourceManager.GetString("StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB.
        /// </summary>
        internal static string TabADB {
            get {
                return ResourceManager.GetString("TabADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesktopWindow.
        /// </summary>
        internal static string TabWin32 {
            get {
                return ResourceManager.GetString("TabWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表：.
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表：.
        /// </summary>
        internal static string TaskListHeader {
            get {
                return ResourceManager.GetString("TaskListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中任务的{0}使用了不存在的任务:&quot;{1}&quot;！.
        /// </summary>
        internal static string TaskNotFoundError {
            get {
                return ResourceManager.GetString("TaskNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务设置.
        /// </summary>
        internal static string TaskSettings {
            get {
                return ResourceManager.GetString("TaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别{0}时发生错误: {1}.
        /// </summary>
        internal static string TaskStackError {
            get {
                return ResourceManager.GetString("TaskStackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题.
        /// </summary>
        internal static string ThemeOption {
            get {
                return ResourceManager.GetString("ThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签顺序可拖动.
        /// </summary>
        internal static string TooltipDragLabel {
            get {
                return ResourceManager.GetString("TooltipDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string TooltipRefresh {
            get {
                return ResourceManager.GetString("TooltipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string TooltipSettings {
            get {
                return ResourceManager.GetString("TooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式.
        /// </summary>
        internal static string InputModeOption {
            get {
                return ResourceManager.GetString("InputModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索窗口!.
        /// </summary>
        internal static string WindowDetectionStarted {
            get {
                return ResourceManager.GetString("WindowDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择窗口:{0}.
        /// </summary>
        internal static string WindowSelectionMessage {
            get {
                return ResourceManager.GetString("WindowSelectionMessage", resourceCulture);
            }
        }
    }
}
