//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAWPF.Res.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFAWPF.Assets.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获模式:.
        /// </summary>
        internal static string AdbCaptureMode {
            get {
                return ResourceManager.GetString("AdbCaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 额外参数.
        /// </summary>
        internal static string AdbConfig {
            get {
                return ResourceManager.GetString("AdbConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb 编辑器.
        /// </summary>
        internal static string AdbEditor {
            get {
                return ResourceManager.GetString("AdbEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdbInput (不推荐).
        /// </summary>
        internal static string AdbInput {
            get {
                return ResourceManager.GetString("AdbInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式:.
        /// </summary>
        internal static string AdbInputMode {
            get {
                return ResourceManager.GetString("AdbInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb名称.
        /// </summary>
        internal static string AdbName {
            get {
                return ResourceManager.GetString("AdbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb路径.
        /// </summary>
        internal static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb地址.
        /// </summary>
        internal static string AdbSerial {
            get {
                return ResourceManager.GetString("AdbSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加至上方.
        /// </summary>
        internal static string AddAbove {
            get {
                return ResourceManager.GetString("AddAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加至下方.
        /// </summary>
        internal static string AddBelow {
            get {
                return ResourceManager.GetString("AddBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        internal static string AdvancedSetting {
            get {
                return ResourceManager.GetString("AdvancedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束后操作.
        /// </summary>
        internal static string AfterTaskOption {
            get {
                return ResourceManager.GetString("AfterTaskOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件 (*.*)|*.*.
        /// </summary>
        internal static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA 任务管理器.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDetect (自动检测).
        /// </summary>
        internal static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动后操作.
        /// </summary>
        internal static string AutoStartOption {
            get {
                return ResourceManager.GetString("AutoStartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获方式.
        /// </summary>
        internal static string CaptureModeOption {
            get {
                return ResourceManager.GetString("CaptureModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前剪贴板中数据不可转换为文本.
        /// </summary>
        internal static string ClipboardDataError {
            get {
                return ResourceManager.GetString("ClipboardDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭模拟器.
        /// </summary>
        internal static string CloseEmulator {
            get {
                return ResourceManager.GetString("CloseEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭MFA和模拟器.
        /// </summary>
        internal static string CloseEmulatorAndMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启MFA和关闭模拟器.
        /// </summary>
        internal static string CloseEmulatorAndRestartMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndRestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭MFA.
        /// </summary>
        internal static string CloseMFA {
            get {
                return ResourceManager.GetString("CloseMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取色器.
        /// </summary>
        internal static string ColorPickerTitle {
            get {
                return ResourceManager.GetString("ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通设置.
        /// </summary>
        internal static string CommonSetting {
            get {
                return ResourceManager.GetString("CommonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接{0}时发生错误！.
        /// </summary>
        internal static string ConnectingEmulatorOrWindow {
            get {
                return ResourceManager.GetString("ConnectingEmulatorOrWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接至{0}.......
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已复制到剪切板.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制错误信息.
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制键.
        /// </summary>
        internal static string CopyKey {
            get {
                return ResourceManager.GetString("CopyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制值.
        /// </summary>
        internal static string CopyValue {
            get {
                return ResourceManager.GetString("CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        internal static string DarkColor {
            get {
                return ResourceManager.GetString("DarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部不选.
        /// </summary>
        internal static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钉钉群发送消息通知.
        /// </summary>
        internal static string DingTalkMessageAsync {
            get {
                return ResourceManager.GetString("DingTalkMessageAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中存在重复的任务名称:&quot;{0}&quot;！.
        /// </summary>
        internal static string DuplicateTaskError {
            get {
                return ResourceManager.GetString("DuplicateTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表中已存在命名为&quot;{0}&quot;的任务.
        /// </summary>
        internal static string DuplicateTaskNameError {
            get {
                return ResourceManager.GetString("DuplicateTaskNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性编辑器.
        /// </summary>
        internal static string EditAttributeDialogTitle {
            get {
                return ResourceManager.GetString("EditAttributeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加属性.
        /// </summary>
        internal static string EditTaskDialog_AddAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_AddAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加任务.
        /// </summary>
        internal static string EditTaskDialog_AddTask_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_AddTask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空属性.
        /// </summary>
        internal static string EditTaskDialog_ClearAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空任务.
        /// </summary>
        internal static string EditTaskDialog_ClearTask_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearTask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取色.
        /// </summary>
        internal static string EditTaskDialog_ColorExtraction_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ColorExtraction_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务编辑器.
        /// </summary>
        internal static string EditTaskDialog_Header {
            get {
                return ResourceManager.GetString("EditTaskDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Pipeline文件.
        /// </summary>
        internal static string EditTaskDialog_Load_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Load_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件名称.
        /// </summary>
        internal static string EditTaskDialog_PipelineFileName_Placeholder {
            get {
                return ResourceManager.GetString("EditTaskDialog_PipelineFileName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字识别.
        /// </summary>
        internal static string EditTaskDialog_RecognitionText_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_RecognitionText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存Pipeline文件.
        /// </summary>
        internal static string EditTaskDialog_SavePipeline_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SavePipeline_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务名称.
        /// </summary>
        internal static string EditTaskDialog_SaveTask_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_SaveTask_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裁剪图片.
        /// </summary>
        internal static string EditTaskDialog_Screenshot_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Screenshot_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择区域.
        /// </summary>
        internal static string EditTaskDialog_SelectionRegion_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SelectionRegion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程图.
        /// </summary>
        internal static string EditTaskDialog_ShowChart_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_ShowChart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滑动.
        /// </summary>
        internal static string EditTaskDialog_Swipe_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Swipe_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表：.
        /// </summary>
        internal static string EditTaskDialog_TaskList_Label {
            get {
                return ResourceManager.GetString("EditTaskDialog_TaskList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务名称:.
        /// </summary>
        internal static string EditTaskDialog_TaskName_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_TaskName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务编辑器.
        /// </summary>
        internal static string EditTaskDialog_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        internal static string EditTaskTooltip {
            get {
                return ResourceManager.GetString("EditTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟器.
        /// </summary>
        internal static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索模拟器!.
        /// </summary>
        internal static string EmulatorDetectionStarted {
            get {
                return ResourceManager.GetString("EmulatorDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟器路径.
        /// </summary>
        internal static string SoftwarePath {
            get {
                return ResourceManager.GetString("SoftwarePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择模拟器:{0}.
        /// </summary>
        internal static string EmulatorSelectionMessage {
            get {
                return ResourceManager.GetString("EmulatorSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用GPU加速.
        /// </summary>
        internal static string EnableGPU {
            get {
                return ResourceManager.GetString("EnableGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用保存截图(用于调试).
        /// </summary>
        internal static string EnableSaveDraw {
            get {
                return ResourceManager.GetString("EnableSaveDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入任务名称.
        /// </summary>
        internal static string EnterTaskName {
            get {
                return ResourceManager.GetString("EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细信息.
        /// </summary>
        internal static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA 遇到了问题.
        /// </summary>
        internal static string ErrorProlog {
            get {
                return ResourceManager.GetString("ErrorProlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可运行文件 (*.exe*)|*.exe*.
        /// </summary>
        internal static string ExeFilter {
            get {
                return ResourceManager.GetString("ExeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        internal static string FollowingSystem {
            get {
                return ResourceManager.GetString("FollowingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片浏览器.
        /// </summary>
        internal static string ImageBrowserTitle {
            get {
                return ResourceManager.GetString("ImageBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件 (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化控制器时发生错误！.
        /// </summary>
        internal static string InitControllerFailed {
            get {
                return ResourceManager.GetString("InitControllerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化控制器成功.
        /// </summary>
        internal static string InitControllerSuccess {
            get {
                return ResourceManager.GetString("InitControllerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化MAA实例失败，发生连接错误或资源文件损坏，请参阅日志..
        /// </summary>
        internal static string InitInstanceFailed {
            get {
                return ResourceManager.GetString("InitInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入资源成功.
        /// </summary>
        internal static string InitResourcesSuccess {
            get {
                return ResourceManager.GetString("InitResourcesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式.
        /// </summary>
        internal static string InputModeOption {
            get {
                return ResourceManager.GetString("InputModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接失败.
        /// </summary>
        internal static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 文件 (*.json)|*.json|所有文件 (*.*)|*.*.
        /// </summary>
        internal static string JSONFilter {
            get {
                return ResourceManager.GetString("JSONFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性类型:.
        /// </summary>
        internal static string LabelPropertyType {
            get {
                return ResourceManager.GetString("LabelPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言(Language).
        /// </summary>
        internal static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        internal static string LightColor {
            get {
                return ResourceManager.GetString("LightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 任意 文件.
        /// </summary>
        internal static string LoadFileTitle {
            get {
                return ResourceManager.GetString("LoadFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择图片文件.
        /// </summary>
        internal static string LoadImageTitle {
            get {
                return ResourceManager.GetString("LoadImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在初始化控制器.
        /// </summary>
        internal static string LoadingController {
            get {
                return ResourceManager.GetString("LoadingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在载入资源.
        /// </summary>
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件加载或解析失败: {0}.
        /// </summary>
        internal static string LoadPipelineErrorMessage {
            get {
                return ResourceManager.GetString("LoadPipelineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 Pipeline 文件.
        /// </summary>
        internal static string LoadPipelineTitle {
            get {
                return ResourceManager.GetString("LoadPipelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源加载失败！.
        /// </summary>
        internal static string LoadResourcesFailed {
            get {
                return ResourceManager.GetString("LoadResourcesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaaTouch (实验功能).
        /// </summary>
        internal static string MaaTouch {
            get {
                return ResourceManager.GetString("MaaTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniTouch (默认).
        /// </summary>
        internal static string MiniTouch {
            get {
                return ResourceManager.GetString("MiniTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到模拟器!.
        /// </summary>
        internal static string NoEmulatorFound {
            get {
                return ResourceManager.GetString("NoEmulatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前没有可结束的任务!.
        /// </summary>
        internal static string NoTaskToStop {
            get {
                return ResourceManager.GetString("NoTaskToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到窗口!.
        /// </summary>
        internal static string NoWindowFound {
            get {
                return ResourceManager.GetString("NoWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴到上方.
        /// </summary>
        internal static string PasteAbove {
            get {
                return ResourceManager.GetString("PasteAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴到下方.
        /// </summary>
        internal static string PasteBelow {
            get {
                return ResourceManager.GetString("PasteBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入Pipeline文件时出现错误: {0}.
        /// </summary>
        internal static string PipelineLoadError {
            get {
                return ResourceManager.GetString("PipelineLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目链接: .
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域选择器.
        /// </summary>
        internal static string RegionSelectorTitle {
            get {
                return ResourceManager.GetString("RegionSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义Action:{0}.
        /// </summary>
        internal static string RegisterCustomAction {
            get {
                return ResourceManager.GetString("RegisterCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义Recognizer:{0}.
        /// </summary>
        internal static string RegisterCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisterCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在注册自定义行动.
        /// </summary>
        internal static string RegisteringCustomAction {
            get {
                return ResourceManager.GetString("RegisteringCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在注册自定义识别器.
        /// </summary>
        internal static string RegisteringCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisteringCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住连接.
        /// </summary>
        internal static string RememberAdb {
            get {
                return ResourceManager.GetString("RememberAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复次数.
        /// </summary>
        internal static string RepeatOption {
            get {
                return ResourceManager.GetString("RepeatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源链接: .
        /// </summary>
        internal static string ResourceLink {
            get {
                return ResourceManager.GetString("ResourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源名称.
        /// </summary>
        internal static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源.
        /// </summary>
        internal static string ResourceOption {
            get {
                return ResourceManager.GetString("ResourceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源版本.
        /// </summary>
        internal static string ResourceVersion {
            get {
                return ResourceManager.GetString("ResourceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启系统.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启MFA.
        /// </summary>
        internal static string RestartMFA {
            get {
                return ResourceManager.GetString("RestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务失败!.
        /// </summary>
        internal static string SaveFailureMessage {
            get {
                return ResourceManager.GetString("SaveFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功！.
        /// </summary>
        internal static string SavePipelineSuccess {
            get {
                return ResourceManager.GetString("SavePipelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表中存在相同命名的任务!.
        /// </summary>
        internal static string SavePipelineWarning {
            get {
                return ResourceManager.GetString("SavePipelineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务成功!.
        /// </summary>
        internal static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截图耗时: {0}ms({1}).
        /// </summary>
        internal static string ScreencapCost {
            get {
                return ResourceManager.GetString("ScreencapCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择可运行文件.
        /// </summary>
        internal static string SelectExecutableFile {
            get {
                return ResourceManager.GetString("SelectExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一张已有图片.
        /// </summary>
        internal static string SelectExistingImage {
            get {
                return ResourceManager.GetString("SelectExistingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关机.
        /// </summary>
        internal static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滑动获取器.
        /// </summary>
        internal static string SliderControlTitle {
            get {
                return ResourceManager.GetString("SliderControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动MFA后启动模拟器.
        /// </summary>
        internal static string StartEmulator {
            get {
                return ResourceManager.GetString("StartEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动任务.
        /// </summary>
        internal static string StartTask {
            get {
                return ResourceManager.GetString("StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动参数.
        /// </summary>
        internal static string StartupParameter {
            get {
                return ResourceManager.GetString("StartupParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动脚本.
        /// </summary>
        internal static string StartupScript {
            get {
                return ResourceManager.GetString("StartupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在停止.......
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止任务失败.
        /// </summary>
        internal static string StoppingFailed {
            get {
                return ResourceManager.GetString("StoppingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止任务.
        /// </summary>
        internal static string StopTask {
            get {
                return ResourceManager.GetString("StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换配置.
        /// </summary>
        internal static string SwitchConfiguration {
            get {
                return ResourceManager.GetString("SwitchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换语言.
        /// </summary>
        internal static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟器.
        /// </summary>
        internal static string TabADB {
            get {
                return ResourceManager.GetString("TabADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桌面应用.
        /// </summary>
        internal static string TabWin32 {
            get {
                return ResourceManager.GetString("TabWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已放弃本次任务.
        /// </summary>
        internal static string TaskAbandoned {
            get {
                return ResourceManager.GetString("TaskAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已全部完成！.
        /// </summary>
        internal static string TaskAllCompleted {
            get {
                return ResourceManager.GetString("TaskAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已全部完成！\n(用时 {0}h {1}m {2}s).
        /// </summary>
        internal static string TaskAllCompletedWithTime {
            get {
                return ResourceManager.GetString("TaskAllCompletedWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已完成.
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表：.
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表：.
        /// </summary>
        internal static string TaskListHeader {
            get {
                return ResourceManager.GetString("TaskListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中任务的{0}使用了不存在的任务:&quot;{1}&quot;！.
        /// </summary>
        internal static string TaskNotFoundError {
            get {
                return ResourceManager.GetString("TaskNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务设置.
        /// </summary>
        internal static string TaskSettings {
            get {
                return ResourceManager.GetString("TaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别{0}时发生错误: {1}.
        /// </summary>
        internal static string TaskStackError {
            get {
                return ResourceManager.GetString("TaskStackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始任务: {0}.
        /// </summary>
        internal static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已中止.
        /// </summary>
        internal static string TaskStopped {
            get {
                return ResourceManager.GetString("TaskStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字识别器.
        /// </summary>
        internal static string TextRecognizerTitle {
            get {
                return ResourceManager.GetString("TextRecognizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题.
        /// </summary>
        internal static string ThemeOption {
            get {
                return ResourceManager.GetString("ThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签顺序可拖动.
        /// </summary>
        internal static string TooltipDragLabel {
            get {
                return ResourceManager.GetString("TooltipDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string TooltipRefresh {
            get {
                return ResourceManager.GetString("TooltipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string TooltipSettings {
            get {
                return ResourceManager.GetString("TooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待模拟器启动时间(秒).
        /// </summary>
        internal static string WaitEmulator {
            get {
                return ResourceManager.GetString("WaitEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待模拟器启动时间(秒): {0}(s).
        /// </summary>
        internal static string WaitSoftwareTime {
            get {
                return ResourceManager.GetString("WaitSoftwareTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法连接至{0}.
        /// </summary>
        internal static string Warning_CannotConnect {
            get {
                return ResourceManager.GetString("Warning_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索窗口!.
        /// </summary>
        internal static string WindowDetectionStarted {
            get {
                return ResourceManager.GetString("WindowDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择窗口:{0}.
        /// </summary>
        internal static string WindowSelectionMessage {
            get {
                return ResourceManager.GetString("WindowSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务流程图.
        /// </summary>
        internal static string WorkflowDiagramTitle {
            get {
                return ResourceManager.GetString("WorkflowDiagramTitle", resourceCulture);
            }
        }
    }
}
